name: bmi_calculator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: '^3.0.0'

dependencies:
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  flutter:       # Required for every Flutter project
    sdk: flutter # Required for every Flutter project
#hexcolor: ^2.0.7
#cupertino_icons: ^1.0.2 # Only required if you use Cupertino (iOS style) icons

dev_dependencies:
  flutter_test:
    sdk: flutter # Required for a Flutter project that includes tests

flutter:

  uses-material-design: true # Required if you use the Material icon font

  assets:  # Lists assets, such as image files
    - assets/images/
     

  #fonts:              # Required if your app uses custom fonts
  #  - family: Schyler
   #   fonts:
    #    - asset: fonts/Schyler-Regular.ttf
     #   - asset: fonts/Schyler-Italic.ttf
      #    style: italic
    #- family: Trajan Pro
     # fonts:
      #  - asset: fonts/TrajanPro.ttf
       # - asset: fonts/TrajanPro_Bold.ttf
        #  weight: 700