// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEGTB--u-dwGxoRpJn6S4ZiVtdllu-V6M',
    appId: '1:444748081532:web:9b61dbc47e64ba3fa69cf9',
    messagingSenderId: '444748081532',
    projectId: 'bmi-mobile-app-f6ef9',
    authDomain: 'bmi-mobile-app-f6ef9.firebaseapp.com',
    storageBucket: 'bmi-mobile-app-f6ef9.appspot.com',
    measurementId: 'G-3EN7M7ZDEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqsulu2t6D8VRSeVLlP8T_uCkQcLP4vK8',
    appId: '1:444748081532:android:f005cb623268f124a69cf9',
    messagingSenderId: '444748081532',
    projectId: 'bmi-mobile-app-f6ef9',
    storageBucket: 'bmi-mobile-app-f6ef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI0qS8mb-OD0CoOpHLl0C41y1LLIaQxRc',
    appId: '1:444748081532:ios:f367fd55207b3612a69cf9',
    messagingSenderId: '444748081532',
    projectId: 'bmi-mobile-app-f6ef9',
    storageBucket: 'bmi-mobile-app-f6ef9.appspot.com',
    iosClientId: '444748081532-ejh84hkbplprsjbr69i32a51k691j075.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmiCalculator',
  );
}
